#!/bin/bash

result=0

for prog in \
  bspwm \
  sxhkd \
  polybar \
  feh \
  compton \
  rofi \
  xsel \
  gnome-screensaver \
  numlockx \
  ibus-daemon \
  xte \
  git \
  st \
  stow \
  vim \
  chromium-browser \
  firefox \
  ranger \
  spotify \
  nautilus \
  /opt/piavpn/bin/pia-client \
  pactl \
  curl \
  dbus-send \
  ; do
    if [ ! $(which $prog) ]; then echo "Missing $prog"; result=1; fi
done

exit $result

