#!/bin/bash

MENU="$(rofi -sep "|" -dmenu -p 'config' <<< "Bspwm|Sxhkd|Polybar")"

case "$MENU" in
    *Bspwm) echo $HOME/.config/bspwm/bspwmrc ;;
    *Sxhkd) echo $HOME/.config/sxhkd/sxhkdrc ;;
    *Polybar) echo $HOME/.config/polybar/config ;;
    *) exit 1 ;;
esac

