#!/bin/bash

main () {
    case "${1:-}" in
        update) "$TERMINAL" -e sudo apt update ;;
        upgrade) "$TERMINAL" -e sudo apt upgrade ;;
        list-x-options) listXOptions ;;
        show) listXOptions | rofimenu ;;
        *) exit 1 ;;
    esac
}

listXOptions () {
    cat <<EOF
{
    "prompt": "option",
    "commands": [
        {
            "description": "Update list",
            "command": "packagectl update"
        },
        {
            "description": "Upgrade",
            "command": "packagectl upgrade"
        }
    ]
}
EOF
}

main "$@"
