#!/bin/sh

RESULT=$(rofi -sep '|' -dmenu -p 'option' <<EOF
Shutdown|Reboot|Sleep|Lock|Logout
EOF
)

case "$RESULT" in
    *Shutdown) shutdown now ;;
    *Reboot) reboot ;;
    *Sleep) systemctl suspend ;;
    *Lock) gnome-screensaver-command -l ;;
    *Logout) bspc quit ;;
    *) exit 1 ;;
esac

