#!/bin/sh

# basic functionality
sxhkd &
feh --bg-fill "$HOME/.config/wallpapers/wallpaper"
compton -b &
polybar main &
gnome-screensaver --no-daemon &
numlockx on
ibus-daemon -dxr
xrdb -merge "$HOME/.Xresources"
redshift-gtk &

# personally used software
/opt/piavpn/bin/pia-client --quiet &

# Bspwm configuration
bspc monitor -d main code communication IV music 

bspc config border_width         2
bspc config window_gap           12
bspc config focused_border_color "#FFB52A"

bspc config automatic_scheme     longest_side
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus       button1
bspc config pointer_modifier     shift

bspc config external_rules_command "$HOME/.config/bspwm/rules"
