format = "${env_var.KUBECTL_CONTEXT}$all"

[directory]
home_symbol = "󰋜"

[env_var.KUBECTL_CONTEXT]
format = "[$symbol$env_value]($style) in "
style = "bold cyan"
symbol = "☸ "

[time]
disabled = false
time_format = "%H:%M"
format = "[$time]($style) "
