#!/bin/sh

d require compfy numlockx ibus-daemon xrdb redshift-gtk nm-applet light-locker

d tools random-wallpaper
compfy -b
numlockx on
ibus-daemon -dxr
xrdb -merge "$HOME/.Xresources"
redshift-gtk &
nm-applet &
light-locker --lock-after-screensaver=0 --lock-on-suspend &

# personally used software
/opt/Mullvad\ VPN/mullvad-gui &
thunderbird
