#!/bin/bash

set -euo pipefail

main () {
    case ${1:-} in
        list-sinks) listSinks ;;
        x-set-default-sink) xSetDefaultSink ;;
        get-volume) CMD=$(d require-one wpctl pactl) && "getVolume-$CMD" ;;
        increase-volume) shift; CMD=$(d require-one wpctl pactl) && "increaseVolume-$CMD" "$@" ;;
        decrease-volume) shift; CMD=$(d require-one wpctl pactl) && "decreaseVolume-$CMD" "$@" ;;
        set-volume) shift; CMD=$(d require-one wpctl pactl) && "setVolume-$CMD" "$@" ;;
        x-set-volume) xSetVolume ;;
        list-x-options) listXOptions ;;
        show) listXOptions | d menu from-json ;;
        *) exit 1 ;;
    esac
}

listSinks () {
    d require pactl awk
    pactl list short sinks | awk '{print $2}'
}

getVolume-wpctl () {
    d require wpctl cut
    wpctl get-volume @DEFAULT_AUDIO_SINK@ | cut -c 11-
}

getVolume-pactl () {
    d require pactl sed head
    pactl get-sink-volume @DEFAULT_SINK@ | head -n1 | sed -E 's/.* ([[:digit:]]+%).*/\1/p;d'
}

increaseVolume-wpctl () {
    d require wpctl printf
    wpctl set-volume @DEFAULT_AUDIO_SINK@ "0.$(printf "%02d" "${1:-5}")+"
}

increaseVolume-pactl () {
    d require pactl
    pactl set-sink-volume @DEFAULT_SINK@ "+${1:-5}%"
}

decreaseVolume-wpctl () {
    d require wpctl printf
    wpctl set-volume @DEFAULT_AUDIO_SINK@ "0.$(printf "%02d" "${1:-5}")-"
}

decreaseVolume-pactl () {
    d require pactl
    pactl set-sink-volume @DEFAULT_SINK@ "-${1:-5}%"
}

setVolume-wpctl () {
    d require wpctl printf
    wpctl set-volume @DEFAULT_AUDIO_SINK@ "0.$(printf "%02d" "${1:?Volume value required.}")"
}

setVolume-pactl () {
    d require pactl
    pactl set-sink-volume @DEFAULT_SINK@ "${1:?Volume value required.}%"
}

xSetDefaultSink () {
    d require pactl
    sink=$(listSinks | d menu dmenu 'select sink') && pactl set-default-sink "$sink"
}

xSetVolume () {
    d require seq printf tr
    local VOLUME
    VOLUME=$(seq 5 5 100 | sed 's/.*/\0%/' | d menu dmenu "Volume" | tr -d '%')
    main set-volume "$VOLUME"
}

listXOptions () {
    cat <<EOF
{
    "prompt": "option",
    "commands": [
        {
            "description": "Set default sink",
            "command": "d audio x-set-default-sink"
        },
        {
            "description": "Set volume",
            "command": "d audio x-set-volume"
        },
        {
            "description": "Increase volume",
            "command": "d audio increase-volume"
        },
        {
            "description": "Decrease volume",
            "command": "d audio decrease-volume"
        }
    ]
}
EOF
}

main "$@"
