#!/bin/bash

set -euo pipefail

# shellcheck source=base.sh
source "$(d script-base)"

CONFIG_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/d
CONFIG_FILE=$CONFIG_DIR/config.toml

d-config-get() {
    d require yq
    local KEY=${1:?Key required}
    local DEFAULT=${2:-}
    [[ -f "$CONFIG_FILE" ]] && yq ".$KEY" "$CONFIG_FILE" || echo "$DEFAULT"
}

d-config-get-arr() {
    d require yq
    local KEY=${1:?Key required}
    yq eval ".${KEY}[]" "$CONFIG_FILE"
}

d-config-edit() {
    "$EDITOR" "$CONFIG_FILE"
}

forward-cmd d-config- "$@"
