#!/bin/bash

set -euo pipefail

# shellcheck source=base.sh
source "$(d script-base)"

# list submodules in a given reposity
d-git-submodules() {
    d require git awk
    workdir=${1:-$(pwd)}
    cd "$workdir" && git submodule | awk -v workdir="$workdir" '{print workdir "/" $2}'
}

forward-cmd d-git- "$@"
