#!/bin/bash

set -euo pipefail

# shellcheck source=base.sh
source "$(d script-base)"

app-exec() {
    if [ "$DESKTOP_SESSION" = "niri" ]; then
        niri msg action spawn -- "$@"
    else
        exec "$@"
    fi
}

d-launch-music() {
    if flatpak list --app | grep ^Spotify; then
        app-exec flatpak run com.spotify.Client
    else
        app-exec spotify --ozone-platform-hint=auto
    fi
}

d-launch-browser() {
    app-exec firefox
}

d-launch-terminal() {
    app-exec kitty -e fish
}

d-launch-editor() {
    app-exec kitty -e nvim
}

d-launch-screenshot() {
    app-exec d tools screenshot
}

forward-cmd d-launch- "$@"
