#!/bin/bash

set -euo pipefail

# shellcheck source=base.sh
source "$(d script-base)"

app-exec() {
    if [ "$DESKTOP_SESSION" = "niri" ]; then
        niri msg action spawn -- "$@"
    else
        exec "$@"
    fi
}

d-launch-music() {
    if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
        app-exec spotify --enable-features=UseOzonePlatform --ozone-platform=wayland
    else
        app-exec spotify
    fi
}

d-launch-browser() {
    app-exec firefox
}

d-launch-terminal() {
    app-exec kitty -e fish
}

d-launch-editor() {
    app-exec kitty -e nvim
}

d-launch-screenshot() {
    app-exec grim -g "$(slurp)" -t ppm - | satty -f - --early-exit
}

forward-cmd d-launch- "$@"
