#!/bin/bash

set -euo pipefail

d require jq rofi

DATA=$(cat "${1:-/dev/stdin}")

PROMPT=$(echo "$DATA" | jq -r '.prompt')
SELECTED=$(echo "$DATA" | jq -r '.commands[].description' | rofi -dmenu -i -p "$PROMPT")
CMD=$(echo "$DATA" | jq -r ".commands | map(select(.description == \"$SELECTED\")) | .[0].command")
eval "$CMD"
