#!/bin/bash

set -euo pipefail

# shellcheck source=base.sh
source "$(d script-base)"

d-menu-from-json() {
    d require jq

    DATA=$(cat "${1:-/dev/stdin}")

    PROMPT=$(echo "$DATA" | jq -r '.prompt')
    SELECTED=$(echo "$DATA" | jq -r '.commands[].description' | d-menu-dmenu "$PROMPT")
    CMD=$(echo "$DATA" | jq -r ".commands | map(select(.description == \"$SELECTED\")) | .[0].command")
    eval "$CMD"
}

d-menu-dmenu() {
    d require wofi

    PROMPT_ARGS=()
    if [ -n "${1:-}" ]; then
        PROMPT_ARGS+=("-p" "$1")
    fi

    rofi -dmenu -i "${PROMPT_ARGS[@]}"
}

forward-cmd d-menu- "$@"
