#!/bin/bash

set -euo pipefail

main () {
    case ${1:-} in
        update|upgrade|upgradable-number|remove-orphans|x-update|x-upgrade|x-remove-orphans)
            "$1" ;;
        list-x-options) listXOptions ;;
        show) listXOptions | d menu ;;
        *) exit 1 ;;
    esac
}

upgradable-number-arch () {
    d require pacman wc
    pacman -Sup | wc -l
}

upgradable-number-ubuntu () {
    d require apt tail wc
    apt list --upgradable | tail -n +2 2> /dev/null | wc -l
}

upgradable-number () {
    if d system os ubuntu; then
        upgradable-number-ubuntu
    elif d system os arch; then
        upgradable-number-arch
    else
        echo "Unrecognized OS"
        exit 1
    fi
}

update-ubuntu () {
    d require apt sudo
    sudo apt update
    echo '---'
    echo Operation finished.
}

update-arch () {
    d require pacman sudo
    sudo pacman -Sy
    echo '---'
    echo Operation finished.
}

update () {
    if d system os ubuntu; then
        update-ubuntu
    elif d system os arch; then
        update-arch
    else
        echo "Unrecognized OS"
        exit 1
    fi
}

x-update() {
    "$TERMINAL" --hold -e d packages update
}

upgrade-arch () {
    d require pacman sudo
    sudo pacman -Syu
    echo '---'
    echo Operation finished.
}

upgrade-ubuntu () {
    d require apt sudo
    sudo apt upgrade
    echo '---'
    echo Operation finished.
}

upgrade () {
    if d system os ubuntu; then
        upgrade-ubuntu
    elif d system os arch; then
        upgrade-arch
    else
        echo "Unrecognized OS"
        exit 1
    fi
}

x-upgrade () {
    "$TERMINAL" --hold -e d packages upgrade
}

remove-orphans-arch () {
    d require pacman sudo

    local ORPHANS
    ORPHANS=$(pacman -Qdtq || true) 
    if [ -z "$ORPHANS" ]; then
        echo There are no orphaned packages.
    else
        echo "2"
        echo -n "$ORPHANS" | sudo pacman -Rns -
        echo '---'
        echo Operation finished.
    fi
}

remove-orphans-ubuntu () {
    d require apt
    echo '---'
    echo TODO
    exit 1
}

remove-orphans () {
    if d system os ubuntu; then
        remove-orphans-ubuntu
    elif d system os arch; then
        remove-orphans-arch
    else
        echo "Unrecognized OS"
        exit 1
    fi
}

x-remove-orphans() {
    "$TERMINAL" --hold -e d packages remove-orphans
}

listXOptions () {
    cat <<EOF
{
    "prompt": "option",
    "commands": [
        {
            "description": "Update list",
            "command": "d packages x-update"
        },
        {
            "description": "Upgrade",
            "command": "d packages x-upgrade"
        },
        {
            "description": "Remove orphaned packages",
            "command": "d packages x-remove-orphans"
        }
    ]
}
EOF
}

main "$@"
