#!/bin/bash

set -euo pipefail
shopt -s nullglob globstar

d require printf ydotool pass head tail yq

list-passwords() {
    local prefix=${PASSWORD_STORE_DIR-~/.password-store}
    local password_files=( "$prefix"/**/*.gpg )
    password_files=( "${password_files[@]#"$prefix"/}" )
    password_files=( "${password_files[@]%.gpg}" )

    printf '%s\n' "${password_files[@]}"
}

dmenu="d menu dmenu"
do_type="ydotool type --key-delay=10 --key-hold=5 --escape=0"
do_tab="ydotool key --key-delay=10 15:1 15:0"
do_enter="ydotool key --key-delay=10 28:1 28:0"

password_entry=$(list-passwords | $dmenu)
data=$(pass show "$password_entry")
password=$(head -n1 <<<"$data")
structured_data=$(tail -n +2 <<<"$data")
username=$(yq '.user' <<<"$structured_data")

[[ -n "$password" ]] || [[ -n "$username" ]] || {
    if type -t notify-send >/dev/null; then
        notify-send --urgency critical "Password or username missing" "$password_entry"
    fi
    exit 1
}

user_pass_option="User <Tab> password"
pass_option="Password"
user_option="User"
user_pass_enter_option="User <Tab> password <Enter>"
pass_enter_option="Password <Enter>"

autofill_options=(
    "$user_pass_option"
    "$pass_option"
    "$user_option"
    "$user_pass_enter_option"
    "$pass_enter_option"
)

option=$(printf '%s\n' "${autofill_options[@]}" | $dmenu)

case $option in
    "$user_pass_option")
        $do_type "$username"
        $do_tab
        $do_type "$password"
        ;;
    "$pass_option") $do_type "$password" ;;
    "$user_option") $do_type "$username" ;;
    "$user_pass_enter_option")
        $do_type "$username"
        $do_tab
        $do_type "$password"
        $do_enter
        ;;
    "$pass_enter_option")
        $do_type "$password"
        $do_enter
        ;;
    *) echo "Unknown option" >&2; exit 1 ;;
esac
