#!/bin/bash

set -euo pipefail

main() {
    case ${1:-} in
        # menu options
        connect) d require scrcpy; scrcpy -d ;;
        connect-screen-off) d require scrcpy; scrcpy -dwS ;;
        # menu handling
        list-x-options) listXOptions ;;
        show) listXOptions | d menu from-json ;;
        *) exit 1 ;;
    esac
}

listXOptions () {
    cat <<EOF
{
    "prompt": "option",
    "commands": [
        {
            "description": "Connect",
            "command": "d phone connect"
        },
        {
            "description": "Connect (screen off, no sleep)",
            "command": "d phone connect-screen-off"
        }
    ]
}
EOF
}

main "$@"
