#!/bin/bash

set -euo pipefail

# shellcheck source=base.sh
source "$(d script-base)"

session=main

d-project-list() {
    d require fd cut xargs wc
    fd --hidden --no-ignore-vcs --type d --max-depth 2 "^\\.git\$" "$(d home)" ~/git | cut -c "$(echo "$HOME/" | wc -c)-" | xargs -n1 dirname
}

d-project-open() {
    local repo
    repo=$(d project list | d menu dmenu "Repository")
    if tmux has -t "$session"; then
        d-project-open-tmux "$repo"
    else
        d-project-open-terminal "$repo"
    fi
}

d-project-open-terminal() {
    local repo
    repo=${1:-$(d project list | d menu dmenu "Repository")}
    $TERMINAL -d "$HOME/$repo" -e "$EDITOR"
}

d-project-open-tmux() {
    local repo
    local display_name
    repo=${1:-$(d project list | d menu dmenu "Repository")}
    display_name=$(basename "$repo")
    tmux new-window -t "$session" -n "$display_name" -c "$HOME/$repo" "$EDITOR"
}

forward-cmd d-project- "$@"
