#!/bin/bash

set -euo pipefail

# shellcheck source=base.sh
source "$(d script-base)"
@setup 'd read ' read

@reg list-documents 'List documents' 1
list-documents() {
    d require fd
    fd -e pdf -e epub '.*' "$HOME/Documents" "$HOME/Downloads"
}

@reg documents 'Documents'
documents() {
    d require zathura
    local DOC
    DOC=$(list-documents | d menu dmenu)
    zathura --fork "$DOC"
}

@main "$@"
