#!/bin/bash

main () {
    case ${1:-} in
        os) shift; os "$@" ;;
        list-x-options) listXOptions ;;
        show) listXOptions | d menu from-json ;;
        *) exit 1 ;;
    esac
}

# get distro info
getField () {
    d require grep cut
    grep "^$1=" /etc/*-release | cut -d= -f2
}

os () {
    local query=$1
    local ID
    local VERSION_ID

    ID=$(getField ID)
    VERSION_ID=$(getField VERSION_ID)

    # construct tag array
    local tags[0]=$ID
    [[ -z "$VERSION_ID" ]] || tags[1]="${ID}_$VERSION_ID"

    if [[ -z "$query" ]]; then
        # output all tags
        for item in "${tags[@]}"
        do
            echo "$item"
        done
    else
        # check if tag is present
        for item in "${tags[@]}"
        do
            [[ "$item" == "$query" ]] && exit 0
        done
        exit 1
    fi

}

listXOptions () {
    local PLAY_PAUSE_OPTION_CONFIG
    local PLAY_PAUSE_OPTION
    PLAY_PAUSE_OPTION_CONFIG=$(d config get toggles.playPauseOption false)
    [[ "$PLAY_PAUSE_OPTION_CONFIG" == "true" ]] && PLAY_PAUSE_OPTION='{ "description": "Play/pause", "command": "sp play" },' || PLAY_PAUSE_OPTION=""
    cat <<EOF
{
    "prompt": "section",
    "commands": [
        $PLAY_PAUSE_OPTION
        {
            "description": "Audio",
            "command": "d audio show"
        },
        {
            "description": "Bluetooth",
            "command": "d bluetooth show"
        },
        {
            "description": "Packages",
            "command": "d packages show"
        },
        {
            "description": "Phone",
            "command": "d phone show"
        },
        {
            "description": "Power",
            "command": "d power show"
        },
        {
            "description": "Read",
            "command": "d read show-menu"
        },
        {
            "description": "Timezones",
            "command": "d tz show"
        },
        {
            "description": "Tools",
            "command": "d tools show"
        },
        {
            "description": "VPN",
            "command": "d vpn show"
        }
    ]
}
EOF
}

main "$@"
