#!/bin/bash

set -euo pipefail

main () {
    case ${1:-} in
        x-connect) x-connect ;;
        x-disconnect) x-disconnect ;;
        list-connected-vpns) list-connected-vpns ;;
        list-x-options) listXOptions ;;
        show) listXOptions | d menu from-json ;;
        *) exit 1 ;;
    esac
}

get-connections-json() {
    d require nmcli sed awk wc
    CONN=$(nmcli -m multiline -f name,uuid,type,active con \
        | sed -r 's/^(.+): +(.+)$/"\1": "\2"/' \
        | awk '{
            if (NR % 4 == 1) printf "  {%s, ",$0;
            else if (NR % 4 == 0) printf "%s}\n",$0;
            else printf "%s, ",$0
        }')
    LN=$(<<<"$CONN" wc -l)

    echo '['
    <<<"$CONN" awk "{ if (NR == $LN) print; else printf \"%s,\\n\",\$0 }"
    echo ']'
}

get-connections-of-type-json() {
    d require jq
    TYPE=${1:?Connection type required}
    ACTIVE=$2
    if [ -z "$ACTIVE" ]; then
        get-connections-json | jq "map(select(.TYPE == \"$TYPE\"))"
    else
        get-connections-json | jq "map(select(.TYPE == \"$TYPE\" and .ACTIVE == \"$ACTIVE\"))"
    fi
}

x-select-type() {
    d require jq sort
    TYPE=${1:?Connection type required}
    ACTIVE=${2:?Connection active state required}
    VPNS=$(get-connections-of-type-json "$TYPE" "$ACTIVE")
    NAMES=$(<<<"$VPNS" jq -r '.[].NAME' | sort)
    CHOICE=$(<<<"$NAMES" d menu dmenu "VPN")
    <<<"$VPNS" jq -r "map(select(.NAME == \"$CHOICE\"))[0].UUID"
}

x-connect () {
    d require nmcli
    VPN=$(x-select-type vpn no)
    nmcli con up "$VPN"
}

x-disconnect () {
    d require nmcli
    VPN=$(x-select-type vpn yes)
    nmcli con down "$VPN"
}

list-connected-vpns () {
    VPNS=$(get-connections-of-type-json vpn yes)
    <<<"$VPNS" jq -r '.[].NAME' | sort
}

listXOptions () {
    cat <<EOF
{
    "prompt": "option",
    "commands": [
        {
            "description": "Connect",
            "command": "d vpn x-connect"
        },
        {
            "description": "Disconnect",
            "command": "d vpn x-disconnect"
        }
    ]
}
EOF
}

main "$@"
