#!/bin/bash

set -euo pipefail

# shellcheck source=base.sh
source "$(d script-base)"

d-widget-music-poll() {
    local _status
    _status=$(sp status || echo -n "")
    if [[ -z "$_status" ]]; then
        echo "󰝚 "
        return 0
    elif [[ "$_status" == "Stopped" ]]; then
        echo " "
        return 0
    elif [[ "$_status" == "Playing" ]]; then
        echo -n "  "
    else
        echo -n "  "
    fi
    eval "$(sp eval)"
    echo "$SPOTIFY_ARTIST - $SPOTIFY_TITLE"
}

d-widget-music-left-click() {
    if pidof 'spotify'; then
        sp play
    else
        d launch music
    fi
}

d-widget-music-middle-click() {
    sp quit
}

d-widget-music-right-click() {
    sp next
}

forward-cmd d-widget-music- "$@"
