alias e="$EDITOR"
alias diskstat='df -x tmpfs -x devtmpfs -x squashfs -h'
alias ls='exa'
alias ll='exa -alh'

cheat() { curl "cheat.sh/$1"; }
pman() { man -t $1 | ps2pdf - - | zathura --fork --mode=fullscreen -; }
