#!/bin/bash

set -euo pipefail

# shellcheck source=base.sh
source "$(d script-base)"

# list all the dotfiles that might be a target for editing
d-dotfiles-list() {
    d require fd
    fd --type f --hidden --ignore --exclude '\.git' . "$DOTFILES_HOME"
}

# list submodules in the dotfiles repository
d-dotfiles-submodules() {
    d require git awk
    d git submodule | awk -v workdir="$DOTFILES_HOME" '{print workdir "/" $2}'
}

# select a dotfile and open it in a editor
d-dotfiles-select() {
    CHOICE=$(d dotfiles list | d menu dmenu file)
    "$TERMINAL" -e "$EDITOR" "$CHOICE"
}

forward-cmd d-dotfiles- "$@"
