#!/bin/bash

set -euo pipefail

# shellcheck source=base.sh
source "$(d script-base)"

d-gnome-eval() {
    d require gdbus
    local expr=${1:?Expression required}
    local result
    result=$(gdbus call --session \
        --dest org.gnome.Shell \
        --object-path /org/gnome/Shell \
        --method org.gnome.Shell.Eval \
        "$expr")

    if [[ "$result" =~ ^\(false ]]; then
        d error "Failed to eval" "Gnome unsafe flag not enabled?"
        return 1
    fi
}

d-gnome-move-window() {
    local titleMatch=${1:?Title match required}
    local x=${2:?X required}
    local y=${3:?Y required}
    local w=${4:?Width required}
    local h=${5:?Height required}
    local workspace=${6:?Workspace required}
    d gnome eval "global.get_window_actors().find(w => w.meta_window.title.includes('$titleMatch') || w.meta_window.wm_class.includes('$titleMatch')).meta_window.move_resize_frame(0, $x, $y, $w, $h)"
    d gnome eval "global.get_window_actors().find(w => w.meta_window.title.includes('$titleMatch') || w.meta_window.wm_class.includes('$titleMatch')).meta_window.change_workspace_by_index($workspace, false)"
}

d-gnome-reset-windows() {
    d require yq
    local layout len
    layout=$(d config get-yaml 'gnome.window-layout')
    len=$(yq length <<<"$layout")
    for i in $(seq 0 $((len - 1))); do
        local item
        item=$(yq ".[$i]" <<<"$layout")
        IFS=$'\n' readarray -t args <<<"$(yq '[.name, .x, .y, .w, .h, .workspace]| .[]' <<<"$item" )"
        d gnome move-window "${args[@]}"
    done
}

forward-cmd d-gnome- "$@"
