#!/bin/bash

set -euo pipefail

# shellcheck source=base.sh
source "$(d script-base)"

session=main

print-dir-if-exists() {
    [ -d "$1" ] && echo "$1"
}

d-project-list() {
    d require fd xargs sort
    cd "$HOME"
    echo .dotfiles
    print-dir-if-exists notes
    print-dir-if-exists notes/work
    fd --hidden --no-ignore-vcs --relative-path --color never --max-depth 2 "^\\.git\$" git | xargs -n1 dirname | sort
}

d-project-open() {
    local repo
    repo=$(d-project-list | d menu dmenu "Repository")
    if tmux has -t "$session"; then
        d-project-open-tmux "$repo"
    else
        d-project-open-terminal "$repo"
    fi
}

d-project-open-terminal() {
    local repo editor
    repo=$HOME/${1:-$(d-project-list | d menu dmenu "Repository")}
    editor=$(d-project-editor-command "$repo")
    $TERMINAL -d "$repo" -e "$editor"
}

d-project-open-tmux() {
    local repo editor display_name
    repo=$HOME/${1:-$(d-project-list | d menu dmenu "Repository")}
    editor=$(d-project-editor-command "$repo")
    display_name=$(basename "$repo")
    tmux new-window -t "$session" -n "$display_name" -c "$repo" "$editor"
}

d-project-editor-command() {
    repo=${1:?"Repository path is required"}
    if [ -r "$repo/shell.nix" ] && d has-cmd 'nix-shell'; then
        echo "nix-shell --command '$EDITOR'"
    else
        echo "$EDITOR"
    fi
}

forward-cmd d-project- "$@"
