#!/bin/bash

set -euo pipefail

# shellcheck source=base.sh
source "$(d script-base)"

d-tmux-pick-window() {
    d require tmux cut
    local S=${1:-main}
    local CHOICE NUM
    CHOICE=$(tmux list-windows -t "$S" -F "#I: #W" | d menu dmenu)
    NUM=$(echo -n "$CHOICE" | cut -d: -f1)
    tmux select-window -t "$S:$NUM"
}

forward-cmd d-tmux- "$@"
