#!/bin/bash

set -euo pipefail

# shellcheck source=base.sh
source "$(d script-base)"

d-widget-volume() {
    echo -n '󰕾  '
    echo -n "$(d audio get-volume)"
    echo '%'
}

d-widget-tz-clock() {
    d require cut date
    local _tz=${1:?Timezone required.}
    local _city
    _city=$(echo -n "$_tz" | cut -d'/' -f2 | tr '_' ' ')
    echo -n "$_city "
    TZ=$_tz date +'%H:%M %Z'
}

forward-cmd d-widget- "$@"
