#!/bin/bash

set -euo pipefail

# shellcheck source=base.sh
source "$(d script-base)"
@setup 'd widget '

@reg volume 'Volume widget'
volume() {
    echo -n '󰕾  '
    echo -n "$(d audio get-volume)"
    echo '%'
}

@reg tz-clock 'Timezone clock widget'
tz-clock() {
    d require cut date
    local _tz=${1:?Timezone required.}
    local _city
    _city=$(echo -n "$_tz" | cut -d'/' -f2 | tr '_' ' ')
    echo -n "$_city "
    TZ=$_tz date +'%H:%M %Z'
}

@reg headset 'Bluetooth headset widget'
headset() {
    d require busctl jq

    local dev_path dev_data connected dev_name percent
    dev_path=$(d config get widgets.main-headset)
    if [[ -z "$dev_path" ]]; then
        echo "󰂯 Headset not configured"
        return
    fi

    dev_data=$(busctl --system -j call org.bluez "$dev_path" org.freedesktop.DBus.Properties GetAll s org.bluez.Device1 | jq '.data[] | map_values(.data)')
    connected=$(jq -r '.Connected' <<< "$dev_data")
    if [[ "$connected" != "true" ]]; then
        echo "󰂲"
        return
    fi

    dev_name=$(jq -r '.Alias' <<< "$dev_data")
    percent=$(busctl --system -j get-property org.bluez "$dev_path" org.bluez.Battery1 Percentage | jq -r '.data')
    echo "󰂯 $dev_name (${percent:-0}%)"
}

@main "$@"
