#!/bin/bash

has-tag() {
    local match_to=$1
    shift
    while [[ $# -gt 0 ]]; do
        if [ "$1" = "$match_to" ]; then
            return 0
        fi
        shift
    done
    return 1
}

link-systemd() {
    local what=${1:?Unit to link required}
    local where
    where=$XDG_CONFIG_HOME/systemd/user/niri.service.wants/$(basename "$what")
    d restore symlink "$what" "$where"
}

[ -f "$HOME/.rcrc" ] && source "$HOME/.rcrc"
if has-tag niri $TAGS; then
    link-systemd "$XDG_CONFIG_HOME/systemd/user/clipse.service"
    link-systemd /usr/lib/systemd/user/gammastep.service
    link-systemd /usr/lib/systemd/user/gammastep-indicator.service
    link-systemd "$XDG_CONFIG_HOME/systemd/user/swww-daemon.service"
    link-systemd /usr/lib/systemd/user/waybar.service
fi
